import Head from 'next/head'
import { Inter } from 'next/font/google'
import { MainCompo } from 'src/components/main.jsx'
import { Header } from 'src/components/Header.jsx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainCompo title="Index"/>
    </div>
  )
}
