import Head from 'next/head'
import { MainCompo } from 'src/components/main.jsx'
import { Header } from 'src/components/Header.jsx'
import { useState } from 'react'

let num = 1;
const Home = (props) => {
  const {
    count, isShow, onClickBtn, changeShow,
    text, array, onChangeText, onAdd,
  } = props;

  const [foo, setFoo] = useState(num);
  return (
    <div>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>{foo}</h1>
      <button onClick={() => {
        hadleClick();
        setFoo(num);
      }}>ボタン</button>
      <button onClick={onClickBtn}>ボタン2</button>
      <button onClick={changeShow}>
        {isShow ? "非表示": "表示"}
      </button>
      {
        isShow ? <h1>{count}</h1>: null
      }


      <input type='text' value={text} onChange={onChangeText}></input>
      <button onClick={onAdd}>追加</button>
      <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul>
      <MainCompo title="Index"/>
    </div>
  )
}

const hadleClick = (e) => {
  num++;
  console.log(num);
}

export default Home
